-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.agent_profiles
(
    agent_profile_id serial NOT NULL,
    user_id character varying(36) COLLATE pg_catalog."default" NOT NULL,
    display_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    is_available boolean NOT NULL,
    customer_tier_id integer,
    max_open_tickets integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT agent_profiles_pkey PRIMARY KEY (agent_profile_id)
);

CREATE TABLE IF NOT EXISTS public.agent_skills
(
    agent_skill_id serial NOT NULL,
    user_id character varying(36) COLLATE pg_catalog."default" NOT NULL,
    area_id bigint NOT NULL,
    proficiency_level character varying(50) COLLATE pg_catalog."default" DEFAULT 'intermediate'::character varying,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT agent_skills_pkey PRIMARY KEY (agent_skill_id),
    CONSTRAINT agent_skills_unique UNIQUE (user_id, area_id)
);

CREATE TABLE IF NOT EXISTS public.areas_of_concern
(
    area_id bigserial NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT areas_of_concern_pkey PRIMARY KEY (area_id),
    CONSTRAINT areas_of_concern_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.business_hours
(
    business_hours_id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    timezone character varying(50) COLLATE pg_catalog."default" NOT NULL,
    monday boolean NOT NULL,
    tuesday boolean NOT NULL,
    wednesday boolean NOT NULL,
    thursday boolean NOT NULL,
    friday boolean NOT NULL,
    saturday boolean NOT NULL,
    sunday boolean NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    CONSTRAINT business_hours_pkey PRIMARY KEY (business_hours_id),
    CONSTRAINT business_hours_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.customer_tiers
(
    tier_id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT customer_tiers_pkey PRIMARY KEY (tier_id),
    CONSTRAINT customer_tiers_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.email_config
(
    config_id serial NOT NULL,
    imap_host character varying(255) COLLATE pg_catalog."default" NOT NULL,
    imap_port integer NOT NULL,
    imap_user character varying(255) COLLATE pg_catalog."default" NOT NULL,
    imap_password character varying(512) COLLATE pg_catalog."default" NOT NULL,
    imap_mailbox character varying(100) COLLATE pg_catalog."default" NOT NULL,
    smtp_host character varying(255) COLLATE pg_catalog."default" NOT NULL,
    smtp_port integer NOT NULL,
    smtp_user character varying(255) COLLATE pg_catalog."default" NOT NULL,
    smtp_password character varying(512) COLLATE pg_catalog."default" NOT NULL,
    smtp_from_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    updated_by character varying(36) COLLATE pg_catalog."default",
    CONSTRAINT email_config_pkey PRIMARY KEY (config_id)
);

CREATE TABLE IF NOT EXISTS public.email_threads
(
    thread_id serial NOT NULL,
    ticket_id bigint,
    message_id character varying(512) COLLATE pg_catalog."default" NOT NULL,
    in_reply_to character varying(512) COLLATE pg_catalog."default",
    raw_subject character varying(500) COLLATE pg_catalog."default" NOT NULL,
    sender_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    received_at timestamp with time zone NOT NULL,
    direction email_direction_enum NOT NULL DEFAULT 'INBOUND'::email_direction_enum,
    raw_body_text text COLLATE pg_catalog."default",
    processed_at timestamp with time zone,
    processing_error character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT email_threads_pkey PRIMARY KEY (thread_id),
    CONSTRAINT email_threads_message_id_key UNIQUE (message_id)
);

CREATE TABLE IF NOT EXISTS public.escalation_history
(
    escalation_id serial NOT NULL,
    ticket_id bigint NOT NULL,
    escalated_by_user_id integer,
    escalated_to_user_id integer NOT NULL,
    reason character varying(500) COLLATE pg_catalog."default" NOT NULL,
    escalated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT escalation_history_pkey PRIMARY KEY (escalation_id)
);

CREATE TABLE IF NOT EXISTS public.keyword_rules
(
    keyword_rule_id serial NOT NULL,
    keyword character varying(255) COLLATE pg_catalog."default" NOT NULL,
    match_field match_field_enum NOT NULL,
    target_severity severity_enum NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT keyword_rules_pkey PRIMARY KEY (keyword_rule_id)
);

CREATE TABLE IF NOT EXISTS public.notification_logs
(
    notification_id serial NOT NULL,
    ticket_id bigint NOT NULL,
    recipient_user_id character varying(36) COLLATE pg_catalog."default" NOT NULL,
    channel notification_channel_enum NOT NULL,
    event_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    status notification_status_enum NOT NULL,
    template_id integer,
    sent_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    is_read boolean NOT NULL DEFAULT false,
    read_at timestamp with time zone,
    CONSTRAINT notification_logs_pkey PRIMARY KEY (notification_id)
);

CREATE TABLE IF NOT EXISTS public.notification_templates
(
    template_id serial NOT NULL,
    event_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    channel notification_channel_enum NOT NULL,
    subject character varying(500) COLLATE pg_catalog."default" NOT NULL,
    body_html text COLLATE pg_catalog."default" NOT NULL,
    body_text text COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT notification_templates_pkey PRIMARY KEY (template_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    is_active boolean NOT NULL,
    CONSTRAINT products_pkey PRIMARY KEY (product_id),
    CONSTRAINT products_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.refresh_tokens
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    jti character varying(36) COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked boolean NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sla_policies
(
    policy_id serial NOT NULL,
    sla_id integer NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    business_hours_only boolean NOT NULL,
    business_hours_id integer,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT sla_policies_pkey PRIMARY KEY (policy_id)
);

CREATE TABLE IF NOT EXISTS public.sla_rules
(
    rule_id serial NOT NULL,
    sla_id integer NOT NULL,
    severity severity_enum NOT NULL,
    priority priority_enum NOT NULL,
    response_time_minutes integer NOT NULL,
    resolution_time_minutes integer NOT NULL,
    escalation_after_minutes integer NOT NULL,
    CONSTRAINT sla_rules_pkey PRIMARY KEY (rule_id),
    CONSTRAINT uq_sla_severity_priority UNIQUE (sla_id, severity, priority)
);

CREATE TABLE IF NOT EXISTS public.slas
(
    sla_id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    customer_tier_id integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT slas_pkey PRIMARY KEY (sla_id)
);

CREATE TABLE IF NOT EXISTS public.ticket_attachments
(
    attachment_id serial NOT NULL,
    ticket_id bigint NOT NULL,
    file_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    file_url character varying(1024) COLLATE pg_catalog."default" NOT NULL,
    uploaded_by_user_id character varying(36) COLLATE pg_catalog."default" NOT NULL,
    uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ticket_attachments_pkey PRIMARY KEY (attachment_id)
);

CREATE TABLE IF NOT EXISTS public.ticket_comments
(
    comment_id serial NOT NULL,
    ticket_id bigint NOT NULL,
    author_id character varying(36) COLLATE pg_catalog."default" NOT NULL,
    author_role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    body text COLLATE pg_catalog."default" NOT NULL,
    is_internal boolean NOT NULL,
    is_mandatory_note boolean NOT NULL,
    triggers_hold boolean NOT NULL,
    triggers_resume boolean NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ticket_comments_pkey PRIMARY KEY (comment_id)
);

CREATE TABLE IF NOT EXISTS public.ticket_embeddings
(
    ticket_id integer NOT NULL,
    embedding vector(768),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ticket_embeddings_pkey PRIMARY KEY (ticket_id)
);

CREATE TABLE IF NOT EXISTS public.ticket_events
(
    event_id serial NOT NULL,
    ticket_id bigint NOT NULL,
    triggered_by_user_id character varying(36) COLLATE pg_catalog."default",
    event_type event_type_enum NOT NULL,
    field_name character varying(100) COLLATE pg_catalog."default",
    old_value character varying(255) COLLATE pg_catalog."default",
    new_value character varying(255) COLLATE pg_catalog."default",
    comment_id integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    from_status character varying(50) COLLATE pg_catalog."default",
    reason character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT ticket_events_pkey PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS public.tickets
(
    ticket_id bigserial NOT NULL,
    ticket_number character varying(20) COLLATE pg_catalog."default" NOT NULL,
    title character varying(500) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    product character varying(100) COLLATE pg_catalog."default" NOT NULL,
    environment environment_enum NOT NULL,
    area_of_concern bigint,
    source ticket_source_enum NOT NULL DEFAULT 'UI'::ticket_source_enum,
    severity severity_enum NOT NULL,
    priority priority_enum NOT NULL,
    status ticket_status_enum NOT NULL DEFAULT 'NEW'::ticket_status_enum,
    customer_id character varying(36) COLLATE pg_catalog."default" NOT NULL,
    assignee_id character varying(36) COLLATE pg_catalog."default",
    queue_type character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'DIRECT'::character varying,
    routing_status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'SUCCESS'::character varying,
    customer_tier_id integer,
    response_sla_deadline_minutes integer,
    resolution_sla_deadline_minutes integer,
    response_sla_started_at timestamp with time zone,
    response_sla_breached_at timestamp with time zone,
    response_sla_completed_at timestamp with time zone,
    first_response_at timestamp with time zone,
    resolution_sla_started_at timestamp with time zone,
    resolution_sla_paused_at timestamp with time zone,
    resolution_sla_total_pause_duration integer NOT NULL DEFAULT 0,
    resolution_sla_completed_at timestamp with time zone,
    resolution_sla_breached_at timestamp with time zone,
    escalation_level integer NOT NULL DEFAULT 0,
    auto_closed boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    is_breached boolean NOT NULL DEFAULT false,
    is_escalated boolean NOT NULL DEFAULT false,
    team_id character varying(36) COLLATE pg_catalog."default",
    fallback_assigned_at timestamp with time zone,
    CONSTRAINT tickets_pkey PRIMARY KEY (ticket_id),
    CONSTRAINT tickets_ticket_number_key UNIQUE (ticket_number)
);

ALTER TABLE IF EXISTS public.agent_profiles
    ADD CONSTRAINT agent_profiles_customer_tier_id_fkey FOREIGN KEY (customer_tier_id)
    REFERENCES public.customer_tiers (tier_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.agent_skills
    ADD CONSTRAINT agent_skills_area_id_fkey FOREIGN KEY (area_id)
    REFERENCES public.areas_of_concern (area_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_agent_skills_area_id
    ON public.agent_skills(area_id);


ALTER TABLE IF EXISTS public.notification_logs
    ADD CONSTRAINT notification_logs_template_id_fkey FOREIGN KEY (template_id)
    REFERENCES public.notification_templates (template_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.sla_policies
    ADD CONSTRAINT sla_policies_business_hours_id_fkey FOREIGN KEY (business_hours_id)
    REFERENCES public.business_hours (business_hours_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.sla_policies
    ADD CONSTRAINT sla_policies_sla_id_fkey FOREIGN KEY (sla_id)
    REFERENCES public.slas (sla_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.sla_rules
    ADD CONSTRAINT sla_rules_sla_id_fkey FOREIGN KEY (sla_id)
    REFERENCES public.slas (sla_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.slas
    ADD CONSTRAINT slas_customer_tier_id_fkey FOREIGN KEY (customer_tier_id)
    REFERENCES public.customer_tiers (tier_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tickets
    ADD CONSTRAINT tickets_area_of_concern_fkey FOREIGN KEY (area_of_concern)
    REFERENCES public.areas_of_concern (area_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.tickets
    ADD CONSTRAINT tickets_customer_tier_id_fkey FOREIGN KEY (customer_tier_id)
    REFERENCES public.customer_tiers (tier_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

END;